micronaut:
  application:
    name: pixKeymanagerGrpc
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/pix
    driverClassName: org.postgresql.Driver
    username: postgres
    password: tomate
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update

itau:
  contas:
    url: ${ITAU_URL:`http://localhost:9091`}
bcb:
  url: ${BCB_URL:`http://localhost:8082/api/v1/pix/keys`}